---
title: "TÜRKİYE’DE E-TİCARET VE ÇEVRİMİÇİ ALIŞVERİŞ YÖNELİMLERİ"
author: 
  - Selam Karakaş[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 17080217, [Github Repo](https://github.com/selamkarakas/arasinav)



# Giriş
E-ticaret günümüzde birçok alanda kullanılmaktadır. İnsanlar evlerinde internet üzerinden gıda ve temel ihtiyaçlar başta olmak üzere sipariş verebilmekte ve ticaret örneği sadece bu olmayıp birçok alana yayılmaktadır. Giyimden teknolojiye akla gelebilecek bütün gereksinimlere internet aracılığı ile sipariş vererek ulaşmak hayatımızın içine yerleşmiştir. İnternette bulunan geniş ürün yelpazesi insanların işlerini birçok alanda zaman tasarrufu sağlayarak halletmelerini kolaylaştırmıştır. E-ticaret alanında hizmet veren işletmelerin sayısı, insanların internet kullanma alışkanlığı ile doğru orantılı olarak her geçen gün artmaktadır. "Türkiye’de hizmet veren konaklama ve yiyecek-içecek sektörü, toptan ve perakende satış yapan sektörleri", @sakar2019real'ın çalışmasındaki 12330 gözlemli veri setinin içinden eleme usulü ile sadeleştirme yaparak “çevrimiçi alışveriş yapanların satın alma niyetinin gerçek zamanlı tahmini” ve "e-ticaret sisteminin ne kadar güvenli olduğu" konularını ele alacağız.

## Çalışmanın Amacı
E-ticaret aracılığıyla mal ve hizmet siparişi alan sektörler ve işletmelerin mal ve hizmet satın alan sektörler ve müşteriler ile arasında ne gibi bir ilişki bulunduğu, ilişki sürecinde aracı rolü üstlenen çevrimiçi sistemlerin güvenlik seviyeleri ve zafiyetleri, ilişkiyi belirli sistem altyapılarıyla kaydedip satın alma sürecinde satın alma amacı, zamanlaması, ödeme yöntemi, tercih sırası, beğenileri ve sıklığı gibi verilerle saptanması ve incelenmesini amaçladığımız bir istatistiksel analiz olacaktır.

## Literatür 
Tanımı gereği bakacak olursak; e-ticaret, klasik ticarete göre çeşitli avantajları barındırmaktadır. İnternet üzerinden gerçekleştiği için girişimcilerin riskleri standart bir girişimciye nazaran daha azdır. İş yeri kirası ve işyerinde çalışan işçiye ödeyeceği maaş, sigorta gibi giderlerinden tasarruf etmektedir. İnternet kullanımı teknolojinin gelişmesi ve genç nüfusun yetişmesine bağlı olarak artmakta, bununla birlikte e-ticaret firmalarının kitlelere ulaşmasında kolaylık sağlanmaktadır. Bu durum rekabetçi bir piyasa oluşumunu da beraberinde getirmektedir [@ozel2013ticaret]. E-ticaret sektöründe artan girişimciler sebebiyle oluşacak pazarın büyümesi ve arz artışlarından dolayı girişimcilerin birbirleriyle olan rekabeti de artacaktır. Bu süreçte mal ve hizmetlerinin piyasada tutunabilmesi için kendilerini sürekli eğitimlerle yenilemeleri gerekecek, piyasaya kaliteli ürünler sunmak zorunda kalacaklardır. Özetle iyi bir esnaf olma tutumunu bu sanal ortama taşımaları gerekecektir. Müşterileri ile iletişimlerini güçlendirerek işlem maliyetlerini azaltabilirler. Nitekim elektronik girişimciliğin klasik ticarete göre; müşteri ürün tercihi, sadık müşteri tespiti, düşük stok maliyeti veya hiç stoksuz çalışma ve ödemenin peşin alınması gibi tartışılmaz üstünlükleri bulunmaktadır [@ozerouglu2018giricsimcilik]. Günümüzde internet ve bilgisayarların kullanımının artmasıyla gelişen e-ticaret sektörünün birçok avantajı yanında dezavantajları da yok değildir. Bilinçli-bilinçsiz teknoloji kullanımı ile eriştiğimiz internet sitelerinde farkında olmadan güvenlik açığı veriyoruz. Oluşan haberlerle insanların bu dünyaya olan önyargıları da artabiliyor. Örneğin internet ödemelerinde kredi kartı bilgilerinin ele geçirilebileceği endişeleri bizim bu sektöre girişimizi erteletebilir. Bu konuyla ilgili yayınlanan @wen2008research araştırmasından bir alıntı yapacak olursak; Çinli araştırmacı yazarlar bu konudaki düşüncelerini şöyle dile getirmişlerdir: ”E-ticaret anlaşmasının ana sorunu güvenlik problemidir, çoğunlukla sistemin güvenliği ve bilgi güvenliği ile ilgili iki görüş vardır. Sistemdeki güvenlik problemlerinin olan sistem internet ortamında ele geçirilmesi, sistemin zarar görmesi, sistemin virüsler tarafından ele geçirilmesi sistemi kesmekte, servisi geciktirmekte ve sistemi etkili bir şekilde yıkmaktadır. Çoğu zaman bilgisayara gizlice giren kişilere engel olmak zordur; bilgi güvenliği problemleri, gizlice dinlenilme, dosyaların sıkıştırılması, bilgi kaybı, yanlış ve sahte bilgiler en yaygın bilgi hırsızlığıdır.” [@gulencc2008lojistik]. Çevrimiçi alışveriş siteleri, müşterilerine en iyi hizmeti sunma amacıyla sistemi fiili olarak bir satış danışmanına çevirecek olan -müşteri telefon, e-posta vb.- bilgilerini alıp, müşteriler web sitesinde gezinirken takibini sağlayarak hangi müşteriye ne içerik sunulacağını, kaybedilme potansiyeli yüksek olan müşteriyi kaçırmama amaçlı teklif sunmayı, satın alma niyeti olan müşteri sayısını çevrimiçi sitede maksimum sayıda tutmayı ve satış için en iyi teklifleri müşterinin ihtiyacına göre belirlemeyi amaçlayan altyapılar geliştirmişlerdir [@sakar2019real].





\newpage
# Kaynakça {#references}
<div id="refs"></div>

